### ISSUE TITLE
Crashes when "click for more information"

### ISSUE THREAD

**Issue by oywino** [sleevezipper/hass-workstation-service#42] opened 2021-03-13 15:45 UTC
Clicking the button "Click for more information" in the Sensor type window CustomCommand, causes the service to crash.

**Comment by sleevezipper** [comment] 2021-03-13 17:21
Hi @oywino! Thanks for creating an issue. This is a duplicate of #33 and had already been fixed. This will be in the next release!

**Closed** 2021-03-13 17:21 UTC
Labels: duplicate
