### ISSUE TITLE
Common sensor name prefix

### ISSUE THREAD

**Issue by robinsmidsrod** [sleevezipper/hass-workstation-service#24] opened 2021-01-18 08:29 UTC
I have multiple computers that I plan to run this service on, so the entity names generated by this application need to be unique. It would therefore be very useful to specify a common prefix (default could be the computer name) that could be added to entity names automatically.

At the same time, each sensor should have an associated human-readable label (e.g. the `LastActiveSensor` should have the label `Last Active`). This way you wouldn't need to manually name any sensor unless you have an unconventional naming scheme.

**Comment by sleevezipper** [comment] 2021-01-18 16:28
Thanks for creating this issue! Home Assistant already appends the entity id with `_2` if it is a duplicate right? Although device name + sensor name would be much cleaner solution. I'll have to do some more research on this later.

**Comment by DevSecNinja** [comment] 2021-01-18 20:06
Came here to ask the same question with regards to the sensor name prefix. I can confirm it appends `_2`. A custom value or `sensor.computername.webcamactive` would be nice as well.

**Comment by sleevezipper** [comment] 2021-02-19 22:14
I did some digging into this and found out the following:

- The `entity_id` in Home Assistant is derived from the sensor name and cannot be explicitly set by MQTT discovery
- The Friendly Name field on entities in Home Assistant cannot be set by MQTT discovery

The only option I can think of is to optionally prefix the sensor/command name with the machine name. The downside of this would be that sensors would be named "Office PC - Last Active" which I personally don't really like. How would you guys feel about this?

**Comment by robinsmidsrod** [comment] 2021-02-20 16:09
@sleevezipper Actually, that example name you mention is what I have mine set to now. Since I have multiple machines going into Home Assistant, and I didn't want the `_2` suffix on all the sensors. If you personally don't like this naming (maybe because you only have a single monitored machine?), what about making it an option which is set to off by default?

Also, considering you call this the "HASS workstation service", how about using the native Home Assistant API to avoid the MQTT discovery naming issues?

**Comment by DevSecNinja** [comment] 2021-02-22 19:49
+1 on the naming convention @robinsmidsrod. Like you I have 2 machines configured with the service and "Office PC - Last Active" would be perfect. @sleevezipper, any reason why you don't like the naming convention like that? Thanks.

**Comment by sleevezipper** [comment] 2021-03-07 01:52
Hey guys,

Just a little update. I agree with both of you that naming the sensors this way is a better approach and I've already done some work on this. I hope to get this into the next release without causing things to break in current configurations.

**Comment by jbstep** [comment] 2021-07-29 13:15
Hey guys,

Trying to switch to this because of the lack of updates and reliability of IOT link. Looks really promising. I have a classroom of 25 computers and being able to use the %computername% variable as a prefix would be perfect. We use a master image to send to the machines fairly often so I need a generic way to set up my sensors that will be consistent across images. I appreciate any suggestions.

**Comment by sleevezipper** [comment] 2021-09-05 20:15
Much later, but here's another update. I've been working on this some more and it has been pretty rough. The current architecture of the application doesn't really lend itself for this use case. I'm not giving up though, so bear with me for a little longer.

**Comment by jbstep** [comment] 2021-09-08 15:11
Awesome, appreciate the effort.

**Comment by sleevezipper** [comment] 2021-10-16 20:27
This has been implemented and will be in the next release!

**Closed by sleevezipper** 2021-10-16 20:27 UTC
Labels: enhancement, next release
