### ISSUE TITLE
WebcamActiveSensor Does Not Update (Logitech c930e, Win 10 19042.685)

### ISSUE THREAD

**Issue by lonelyseraphim** [sleevezipper/hass-workstation-service#18] opened 2021-01-11 19:43 UTC
WebcamActiveSensor does not update from "False" to "True" when webcam is in use.  Sensor fails to update using Zoom client, webcamtests.com, and integrated windows 10 camera app despite operating correctly in all applications.

Webcam: Logitech c930e (USB)
Drivers: v 1.2.75.33, provided on 5/13/2020 by Logitech

OS: Windows 10 Pro, Version 20H2, OS build 19042.685

**Comment by sleevezipper** [comment] 2021-01-11 19:49
Thank you for creating an issue!

I actually had the same problem with my work laptop today so I can at least reproduce it. My guess it that is has something to do with where Windows saves the last accessed data. Sometimes it seems to be in HKEY_CURRENT_USER and sometimes in HKEY_LOCAL_MACHINE. I think this sensor should actually check both and so does the microphone sensor.

**Comment by rEs-84** [comment] 2021-01-12 19:29
Have the same issue on a dell Latitude laptop 
Windows 10 20H1 (updated to 20H2 and still the same).

The webcam (Integrated webcam) and microphone (Realtek Audio) sensors appear to do nothing. 

Tried teams (taskbar shows that something is using my mic) and windows camera app

**Comment by rEs-84** [comment] 2021-01-12 19:53
Webcam Registry Key:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\
Microphone Registry Key:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\
![image](https://user-images.githubusercontent.com/34245082/104365268-b4bba980-550f-11eb-8876-ff5d6655c204.png)

![image](https://user-images.githubusercontent.com/34245082/104365291-bb4a2100-550f-11eb-9610-3e07af3071e4.png)

the page you linked in your feature request, mentions about tracking history of usage. mine doesnt appear too

**Comment by sleevezipper** [comment] 2021-01-12 20:27
Hi @rEs-84! 

If you scroll down to the bottom on that settings screen, do you see more entries there? Do they have a date and time for last accessed?

**Comment by sleevezipper** [comment] 2021-01-12 21:49
I think I fixed it. Could any of you try [this standalone release](https://hassworkstationstorage.blob.core.windows.net/$web/releases/standalone-webcamfix.zip)?

**Comment by rEs-84** [comment] 2021-01-12 22:30
yeah that seems to have done the trick.

Out of interest how are you detecting the webcam and mic are in use, still registry (but somewhere else?)
i'm only interested in the mic monitoring, to mute my radio when on calls.

I did have a few issues getting the new version to actually connect to mqtt, but I think killing the previous app running in the background as an admin account, might of resolved it. So i assume two copies cant be ran on same machine (not issue for me).

Maybe enable a taskbar icon so the app can be closed / config got to easily etc?

**Comment by lonelyseraphim** [comment] 2021-01-13 14:13
The standalone install seems to have worked for me too!  Nice work!

**Comment by sleevezipper** [comment] 2021-01-13 20:19
Thanks for testing this both of you! I'm going to mark this as closed and the fix will be in the next release. If anyone comes across this, you can use the file I linked a few comments up if you don;t want to wait for next release.

@rEs-84, yes, it's still registry. The following sub registries are available: 
![afbeelding](https://user-images.githubusercontent.com/4253662/104505667-8eb40900-55e4-11eb-9bc3-c8a602ee954b.png)
I was only checking HKEY_LOCAL_MACHINE while some entries appear in HKEY_CURRENT_USER. This may have something to do with how application are installed, either as user or for the whole machine but I'm not sure about that.

**Closed by sleevezipper** 2021-01-13 20:19 UTC
Labels: bug
