### ISSUE TITLE
Ability to Edit sensors and commands

### ISSUE THREAD

**Issue by haddood** [sleevezipper/hass-workstation-service#61] opened 2021-03-22 09:12 UTC
Hi,
Thanks for this amazing tool. it would be nice if we can edit a sensor or a command after it is created

**Comment by sleevezipper** [comment] 2021-03-22 09:15
Thanks for the kind words! This is a duplicate of #17 so I'll close it. Please upvote (and follow) that issue instead.

**Closed** 2021-03-22 09:15 UTC
Labels: duplicate, enhancement
