### ISSUE TITLE
Session State remains unknown

### ISSUE THREAD

**Issue by Chreece** [sleevezipper/hass-workstation-service#39] opened 2021-02-19 11:09 UTC
Hello,

I want to thank you for your time creating something so useful! I am sure it will grow up and will be a top app/service for all IOT users.
I have migrated from IOTLink since I had some issues with reconnections after hibernate and it seems a dead project since there is no recently update.

Unfortunately I couldn't get the Session State sensor to work. It stays in unknown state.

Is there something to do about it?

**Comment by sleevezipper** [comment] 2021-02-19 17:49
Hi! Thank you for the kind words.

This could be a permission issue. Does your device have any restrictions set by your employer?

**Comment by Chreece** [comment] 2021-02-19 17:51
Thank you for your answer!
No it's a private laptop, I can try whatever you have to suggest me :)

**Comment by sleevezipper** [comment] 2021-02-19 19:56
Haha nice.

Just to verify, other sensor types work like they should?

**Comment by Chreece** [comment] 2021-02-19 21:37
Yes, i.e. Last Active and Active Window are working great!

**Comment by sleevezipper** [comment] 2021-02-19 22:18
Cool. I'll cook up a new build this weekend with some extra logging as I can't reproduce this. Did you use the installer or the standalone?

**Comment by Chreece** [comment] 2021-02-20 09:09
That sounds great! I did use the installer

**Comment by sleevezipper** [comment] 2021-02-21 22:07
This is gonna take me a bit longer, sorry about that. The company I work at will be moving this week and I needed to do the network infrastructure and servers at the new location.

**Comment by Chreece** [comment] 2021-02-23 18:48
Are you serious? I'm not your Boss!
Please ignore my issue, I have to thank you for your time involving in a service application that I get to use for free :)

**Comment by sleevezipper** [comment] 2021-03-06 13:44
Hi @Chreece,

I finally got to this. Hope I didn't keep you waiting for too long. 

There's a few steps to follow:

1. Download [this](https://hassworkstationstorage.blob.core.windows.net/$web/releases/Chreese%20-debug.zip) and unpack it somewhere
2. Kill hass-workstation-service.exe in task manager
3. Run hass-workstation-service.exe you just unpacked
4. Run UserInterface.exe so you can see the sensor failing
5. Press Win + R and paste this: %localappdata%\Hass Workstation Service\logs
6. Send me the newest file

**Comment by sleevezipper** [comment] 2021-03-06 14:40
Thanks for working with me on Discord @Chreece. This was fixed in a8f749557fd8724930d29470b00358b8d8e9cc32 and will be in the next release.

**Closed by sleevezipper** 2021-03-06 14:40 UTC
